name: Go

on:
  create:
    tags:
    - v*.*.*

jobs:
  test:
      name: Test
      runs-on: ubuntu-latest
      steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
  
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
  
      - name: Get dependencies
        run: go get -v -t -d ./...
  
      - name: Test code
        run: go test -v github.com/m-88888888/bk/...

  setup-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
